### ISSUE TITLE
Earlier instantiation

### ISSUE THREAD

**Issue by christophlehmann** [networkteam/sentry_client#71]
Sentry has an Integration for catching Errors that occur when reaching `memory_limit`. Currently this is not active. The client needs to be setup earlier.

**Comment by kitzberger** [comment]
@christophlehmann, is this catching of "Allowed memory size ..." actually working in 5.1.1? Because I got nothing in Sentry on those incidents ;-(

I implemented something like this in `config/system/additional.php` to have them be reported to a Slack channel...
```php
function shutdown()
{
    if ($error = error_get_last()) {
        if (str_contains($error['message'], 'Allowed memory size')) {
            $error['environment'] = (string)\TYPO3\CMS\Core\Core\Environment::getContext();
            $error['url'] = "https://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
            
            // Slack webhook via cURL.
            ...

            exit();
        }
    }
}

register_shutdown_function('shutdown');
```

Maybe something like this could be implemented into EXT:sentry_client?

**Comment by christophlehmann** [comment]
@kitzberger https://docs.sentry.io/platforms/php/integrations/#errorlistenerintegration cares about these memory errors. If it does not work, would you like to have a deeper look?
