### ISSUE TITLE
"messageBlacklistRegex" Setting array with multiple Expression instead of one string

### ISSUE THREAD

**Issue by Fanor51** [networkteam/sentry_client#80]
Hello,

I have a question about the settings "messageBlacklistRegex". I want to add multiple regex expressions to be ignored, but only have one string to put it in. My question is: How do you manage multiple exceptions to be excluded? Do you write them all in one expression with the Pipe ( | ) Operator?

My Suggestion would be that the "messageBlacklistRegex" gets from string to array and that you can add every statement standalone. 

What do you think about it?
If it's needed, I would build this and pr you.

Best Regards
Fabio

**Comment by christophlehmann** [comment]
Hey Fabio,

thanks for addressing this. You are absolutely right, the setting could be better readable if its an array. 

We don't use it that often (more as a hotfix) and since v11 most of the noisy superfluous Exceptions were muted in core, so most of the time the setting is empty for us. For that reason, i wouldn't put time into it.

>Do you write them all in one expression with the Pipe ( | ) Operator?
yes

A very good place to mute them for everyone is here: https://github.com/TYPO3-CMS/core/blob/main/Classes/Error/AbstractExceptionHandler.php#L45

**Comment by Fanor51** [comment]
Hello @christophlehmann ,

thank you very much for the answer!

Okay alright, I get the point. Is there a smart way to overwrite or extend the core ExceptionHandler or do i have to overwrite it via xclass or composer patch?

Best Regards
Fabio

**Comment by christophlehmann** [comment]
>A very good place to mute

What i meaned is, to make a PR in TYPO3 CMS to mute them for all of us forever ;-)

**Comment by dahaupt** [comment]
@christophlehmann Unfortunately, the exceptions muted by the core are still captured with the configured `config.contentObjectExceptionHandler` which is \Networkteam\SentryClient\Content\ProductionExceptionHandler`.

What about adding a condition for those in `\Networkteam\SentryClient\Service\ExceptionBlacklistService::shouldHandleException`?
